<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Acceso_Localidad.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proyecto1\Entidades.csproj" />
  </ItemGroup>

</Project>
